version: '3'

services:
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always


  postgresDB:
    image: 'postgres:alpine'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: IAmTheUser
      POSTGRES_PASSWORD: ThisIsMyPassword


  rabbitMQ:
    image: 'rabbitmq:3.13-management-alpine'
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: IAmTheUser
      RABBITMQ_DEFAULT_PASS: ThisIsMyPassword


  