version: '3'

services:
  mailhog:
    image: 'mailhog/mailhog:latest'
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: always


  postgresDB:
    image: 'postgres:alpine'
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: IAmTheUser
      POSTGRES_PASSWORD: ThisIsMyPassword


  rabbitMQ:
    image: 'rabbitmq:3.13-management'
    ports:
      - "5552:5552"
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: IAmTheUser
      RABBITMQ_DEFAULT_PASS: ThisIsMyPassword
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: '-rabbitmq_stream advertised_host localhost -rabbit loopback_users "none"'

  
  redisDB:
    image: 'redis:alpine'
    ports:
      - "6379:6379"
    restart: always


  