pipeline{
    agent any

    stages{
        stage("auth-test"){
            agent {
                dockerfile {
                    filename 'Dockerfile.jenkins'     // Pfad zu deinem Dockerfile                          // optional: Build-Verzeichnis
                    additionalBuildArgs ''            // optional: extra build args
                    args '--network host -u root -v /var/run/docker.sock:/var/run/docker.sock'
                    reuseNode true
                }
            }
            steps{
                echo "========executing auth-test========"
                echo "======== Installing Dependencies ========"
                sh '''
                    apk add --no-cache bash git docker-cli postgresql-client
                    go mod download
                '''

                echo "======== Running Tests ========"
                sh 'go test -v ./...'
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========auth-test executed successfully========"
                }
                failure{
                    echo "========auth-test execution failed========"
                }
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}