package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"
	"user_manager/graph/model"
)

// CreateWorkspace is the resolver for the createWorkspace field.
func (r *mutationResolver) CreateWorkspace(ctx context.Context, input model.WorkspaceCredentials) (*model.Workspace, error) {
	panic(fmt.Errorf("not implemented: CreateWorkspace - createWorkspace"))
}

// SendInvitation is the resolver for the sendInvitation field.
func (r *mutationResolver) SendInvitation(ctx context.Context, credentials model.InvitationCredentials) (string, error) {
	panic(fmt.Errorf("not implemented: SendInvitation - sendInvitation"))
}

// SendJoinRequest is the resolver for the sendJoinRequest field.
func (r *mutationResolver) SendJoinRequest(ctx context.Context, credentials model.JoinRequestCredentials) (string, error) {
	panic(fmt.Errorf("not implemented: SendJoinRequest - sendJoinRequest"))
}

// GetUser is the resolver for the getUser field.
func (r *queryResolver) GetUser(ctx context.Context, entity string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: GetUser - getUser"))
}

// GetInvitationInfos is the resolver for the getInvitationInfos field.
func (r *queryResolver) GetInvitationInfos(ctx context.Context, userID string) ([]*model.InvitationInfo, error) {
	panic(fmt.Errorf("not implemented: GetInvitationInfos - getInvitationInfos"))
}

// GetJoinRequestInfos is the resolver for the getJoinRequestInfos field.
func (r *queryResolver) GetJoinRequestInfos(ctx context.Context, workspaceID string) ([]*model.JoinRequestInfo, error) {
	panic(fmt.Errorf("not implemented: GetJoinRequestInfos - getJoinRequestInfos"))
}

// LookupWorkspace is the resolver for the lookupWorkspace field.
func (r *queryResolver) LookupWorkspace(ctx context.Context, workspaceID string) (*model.CompleteWorkspace, error) {
	panic(fmt.Errorf("not implemented: LookupWorkspace - lookupWorkspace"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}
*/
