// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.0
// source: key_orchestrator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InitKeySubscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitKeySubscription) Reset() {
	*x = InitKeySubscription{}
	mi := &file_key_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitKeySubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitKeySubscription) ProtoMessage() {}

func (x *InitKeySubscription) ProtoReflect() protoreflect.Message {
	mi := &file_key_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitKeySubscription.ProtoReflect.Descriptor instead.
func (*InitKeySubscription) Descriptor() ([]byte, []int) {
	return file_key_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *InitKeySubscription) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *InitKeySubscription) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Retry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Retry) Reset() {
	*x = Retry{}
	mi := &file_key_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Retry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Retry) ProtoMessage() {}

func (x *Retry) ProtoReflect() protoreflect.Message {
	mi := &file_key_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Retry.ProtoReflect.Descriptor instead.
func (*Retry) Descriptor() ([]byte, []int) {
	return file_key_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *Retry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type NewKey struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewKey) Reset() {
	*x = NewKey{}
	mi := &file_key_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewKey) ProtoMessage() {}

func (x *NewKey) ProtoReflect() protoreflect.Message {
	mi := &file_key_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewKey.ProtoReflect.Descriptor instead.
func (*NewKey) Descriptor() ([]byte, []int) {
	return file_key_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *NewKey) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type KeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyResponse) Reset() {
	*x = KeyResponse{}
	mi := &file_key_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyResponse) ProtoMessage() {}

func (x *KeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyResponse.ProtoReflect.Descriptor instead.
func (*KeyResponse) Descriptor() ([]byte, []int) {
	return file_key_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *KeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *KeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetKeyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*GetKeyRequest_InitKeySubscription
	//	*GetKeyRequest_Retry
	//	*GetKeyRequest_NewKey
	Payload       isGetKeyRequest_Payload `protobuf_oneof:"Payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyRequest) Reset() {
	*x = GetKeyRequest{}
	mi := &file_key_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyRequest) ProtoMessage() {}

func (x *GetKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_orchestrator_proto_rawDescGZIP(), []int{4}
}

func (x *GetKeyRequest) GetPayload() isGetKeyRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *GetKeyRequest) GetInitKeySubscription() *InitKeySubscription {
	if x != nil {
		if x, ok := x.Payload.(*GetKeyRequest_InitKeySubscription); ok {
			return x.InitKeySubscription
		}
	}
	return nil
}

func (x *GetKeyRequest) GetRetry() *Retry {
	if x != nil {
		if x, ok := x.Payload.(*GetKeyRequest_Retry); ok {
			return x.Retry
		}
	}
	return nil
}

func (x *GetKeyRequest) GetNewKey() *NewKey {
	if x != nil {
		if x, ok := x.Payload.(*GetKeyRequest_NewKey); ok {
			return x.NewKey
		}
	}
	return nil
}

type isGetKeyRequest_Payload interface {
	isGetKeyRequest_Payload()
}

type GetKeyRequest_InitKeySubscription struct {
	InitKeySubscription *InitKeySubscription `protobuf:"bytes,1,opt,name=init_key_subscription,json=initKeySubscription,proto3,oneof"`
}

type GetKeyRequest_Retry struct {
	Retry *Retry `protobuf:"bytes,2,opt,name=retry,proto3,oneof"`
}

type GetKeyRequest_NewKey struct {
	NewKey *NewKey `protobuf:"bytes,3,opt,name=new_key,json=newKey,proto3,oneof"`
}

func (*GetKeyRequest_InitKeySubscription) isGetKeyRequest_Payload() {}

func (*GetKeyRequest_Retry) isGetKeyRequest_Payload() {}

func (*GetKeyRequest_NewKey) isGetKeyRequest_Payload() {}

var File_key_orchestrator_proto protoreflect.FileDescriptor

const file_key_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x16key_orchestrator.proto\x12\x18key_orchestrator_service\"9\n" +
	"\x13InitKeySubscription\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"\x17\n" +
	"\x05Retry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x18\n" +
	"\x06NewKey\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\vKeyResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\"\xf5\x01\n" +
	"\rGetKeyRequest\x12c\n" +
	"\x15init_key_subscription\x18\x01 \x01(\v2-.key_orchestrator_service.InitKeySubscriptionH\x00R\x13initKeySubscription\x127\n" +
	"\x05retry\x18\x02 \x01(\v2\x1f.key_orchestrator_service.RetryH\x00R\x05retry\x12;\n" +
	"\anew_key\x18\x03 \x01(\v2 .key_orchestrator_service.NewKeyH\x00R\x06newKeyB\t\n" +
	"\aPayload2w\n" +
	"\x16KeyOrchestratorService\x12]\n" +
	"\aKeyPipe\x12'.key_orchestrator_service.GetKeyRequest\x1a%.key_orchestrator_service.KeyResponse(\x010\x01B\tZ\a./protob\x06proto3"

var (
	file_key_orchestrator_proto_rawDescOnce sync.Once
	file_key_orchestrator_proto_rawDescData []byte
)

func file_key_orchestrator_proto_rawDescGZIP() []byte {
	file_key_orchestrator_proto_rawDescOnce.Do(func() {
		file_key_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_orchestrator_proto_rawDesc), len(file_key_orchestrator_proto_rawDesc)))
	})
	return file_key_orchestrator_proto_rawDescData
}

var file_key_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_key_orchestrator_proto_goTypes = []any{
	(*InitKeySubscription)(nil), // 0: key_orchestrator_service.InitKeySubscription
	(*Retry)(nil),               // 1: key_orchestrator_service.Retry
	(*NewKey)(nil),              // 2: key_orchestrator_service.NewKey
	(*KeyResponse)(nil),         // 3: key_orchestrator_service.KeyResponse
	(*GetKeyRequest)(nil),       // 4: key_orchestrator_service.GetKeyRequest
}
var file_key_orchestrator_proto_depIdxs = []int32{
	0, // 0: key_orchestrator_service.GetKeyRequest.init_key_subscription:type_name -> key_orchestrator_service.InitKeySubscription
	1, // 1: key_orchestrator_service.GetKeyRequest.retry:type_name -> key_orchestrator_service.Retry
	2, // 2: key_orchestrator_service.GetKeyRequest.new_key:type_name -> key_orchestrator_service.NewKey
	4, // 3: key_orchestrator_service.KeyOrchestratorService.KeyPipe:input_type -> key_orchestrator_service.GetKeyRequest
	3, // 4: key_orchestrator_service.KeyOrchestratorService.KeyPipe:output_type -> key_orchestrator_service.KeyResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_key_orchestrator_proto_init() }
func file_key_orchestrator_proto_init() {
	if File_key_orchestrator_proto != nil {
		return
	}
	file_key_orchestrator_proto_msgTypes[4].OneofWrappers = []any{
		(*GetKeyRequest_InitKeySubscription)(nil),
		(*GetKeyRequest_Retry)(nil),
		(*GetKeyRequest_NewKey)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_orchestrator_proto_rawDesc), len(file_key_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_orchestrator_proto_goTypes,
		DependencyIndexes: file_key_orchestrator_proto_depIdxs,
		MessageInfos:      file_key_orchestrator_proto_msgTypes,
	}.Build()
	File_key_orchestrator_proto = out.File
	file_key_orchestrator_proto_goTypes = nil
	file_key_orchestrator_proto_depIdxs = nil
}
