// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.0
// source: key_orchestrator.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyRequest) Reset() {
	*x = GetKeyRequest{}
	mi := &file_key_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyRequest) ProtoMessage() {}

func (x *GetKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *GetKeyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetKeyRequest) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type KeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyResponse) Reset() {
	*x = KeyResponse{}
	mi := &file_key_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyResponse) ProtoMessage() {}

func (x *KeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyResponse.ProtoReflect.Descriptor instead.
func (*KeyResponse) Descriptor() ([]byte, []int) {
	return file_key_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *KeyResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *KeyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *KeyResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

var File_key_orchestrator_proto protoreflect.FileDescriptor

const file_key_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x16key_orchestrator.proto\x12\x18key_orchestrator_service\"5\n" +
	"\rGetKeyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"I\n" +
	"\vKeyResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key2w\n" +
	"\x16KeyOrchestratorService\x12]\n" +
	"\aKeyPipe\x12'.key_orchestrator_service.GetKeyRequest\x1a%.key_orchestrator_service.KeyResponse(\x010\x01B\tZ\a./protob\x06proto3"

var (
	file_key_orchestrator_proto_rawDescOnce sync.Once
	file_key_orchestrator_proto_rawDescData []byte
)

func file_key_orchestrator_proto_rawDescGZIP() []byte {
	file_key_orchestrator_proto_rawDescOnce.Do(func() {
		file_key_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_orchestrator_proto_rawDesc), len(file_key_orchestrator_proto_rawDesc)))
	})
	return file_key_orchestrator_proto_rawDescData
}

var file_key_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_key_orchestrator_proto_goTypes = []any{
	(*GetKeyRequest)(nil), // 0: key_orchestrator_service.GetKeyRequest
	(*KeyResponse)(nil),   // 1: key_orchestrator_service.KeyResponse
}
var file_key_orchestrator_proto_depIdxs = []int32{
	0, // 0: key_orchestrator_service.KeyOrchestratorService.KeyPipe:input_type -> key_orchestrator_service.GetKeyRequest
	1, // 1: key_orchestrator_service.KeyOrchestratorService.KeyPipe:output_type -> key_orchestrator_service.KeyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_key_orchestrator_proto_init() }
func file_key_orchestrator_proto_init() {
	if File_key_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_orchestrator_proto_rawDesc), len(file_key_orchestrator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_orchestrator_proto_goTypes,
		DependencyIndexes: file_key_orchestrator_proto_depIdxs,
		MessageInfos:      file_key_orchestrator_proto_msgTypes,
	}.Build()
	File_key_orchestrator_proto = out.File
	file_key_orchestrator_proto_goTypes = nil
	file_key_orchestrator_proto_depIdxs = nil
}
