// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.0
// source: key_orchestrator.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyOrchestratorService_KeyPipe_FullMethodName = "/key_orchestrator_service.KeyOrchestratorService/KeyPipe"
)

// KeyOrchestratorServiceClient is the client API for KeyOrchestratorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyOrchestratorServiceClient interface {
	KeyPipe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GetKeyRequest, KeyResponse], error)
}

type keyOrchestratorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyOrchestratorServiceClient(cc grpc.ClientConnInterface) KeyOrchestratorServiceClient {
	return &keyOrchestratorServiceClient{cc}
}

func (c *keyOrchestratorServiceClient) KeyPipe(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[GetKeyRequest, KeyResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &KeyOrchestratorService_ServiceDesc.Streams[0], KeyOrchestratorService_KeyPipe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetKeyRequest, KeyResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeyOrchestratorService_KeyPipeClient = grpc.BidiStreamingClient[GetKeyRequest, KeyResponse]

// KeyOrchestratorServiceServer is the server API for KeyOrchestratorService service.
// All implementations must embed UnimplementedKeyOrchestratorServiceServer
// for forward compatibility.
type KeyOrchestratorServiceServer interface {
	KeyPipe(grpc.BidiStreamingServer[GetKeyRequest, KeyResponse]) error
	mustEmbedUnimplementedKeyOrchestratorServiceServer()
}

// UnimplementedKeyOrchestratorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyOrchestratorServiceServer struct{}

func (UnimplementedKeyOrchestratorServiceServer) KeyPipe(grpc.BidiStreamingServer[GetKeyRequest, KeyResponse]) error {
	return status.Errorf(codes.Unimplemented, "method KeyPipe not implemented")
}
func (UnimplementedKeyOrchestratorServiceServer) mustEmbedUnimplementedKeyOrchestratorServiceServer() {
}
func (UnimplementedKeyOrchestratorServiceServer) testEmbeddedByValue() {}

// UnsafeKeyOrchestratorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyOrchestratorServiceServer will
// result in compilation errors.
type UnsafeKeyOrchestratorServiceServer interface {
	mustEmbedUnimplementedKeyOrchestratorServiceServer()
}

func RegisterKeyOrchestratorServiceServer(s grpc.ServiceRegistrar, srv KeyOrchestratorServiceServer) {
	// If the following call pancis, it indicates UnimplementedKeyOrchestratorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyOrchestratorService_ServiceDesc, srv)
}

func _KeyOrchestratorService_KeyPipe_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(KeyOrchestratorServiceServer).KeyPipe(&grpc.GenericServerStream[GetKeyRequest, KeyResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type KeyOrchestratorService_KeyPipeServer = grpc.BidiStreamingServer[GetKeyRequest, KeyResponse]

// KeyOrchestratorService_ServiceDesc is the grpc.ServiceDesc for KeyOrchestratorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyOrchestratorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "key_orchestrator_service.KeyOrchestratorService",
	HandlerType: (*KeyOrchestratorServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "KeyPipe",
			Handler:       _KeyOrchestratorService_KeyPipe_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "key_orchestrator.proto",
}
