// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.27.0
// source: credential_distro.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SubscribeToSaltDistro struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToSaltDistro) Reset() {
	*x = SubscribeToSaltDistro{}
	mi := &file_credential_distro_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToSaltDistro) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToSaltDistro) ProtoMessage() {}

func (x *SubscribeToSaltDistro) ProtoReflect() protoreflect.Message {
	mi := &file_credential_distro_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToSaltDistro.ProtoReflect.Descriptor instead.
func (*SubscribeToSaltDistro) Descriptor() ([]byte, []int) {
	return file_credential_distro_proto_rawDescGZIP(), []int{0}
}

func (x *SubscribeToSaltDistro) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeToSaltDistro) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type SubscribeToConnectionCredRotator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeToConnectionCredRotator) Reset() {
	*x = SubscribeToConnectionCredRotator{}
	mi := &file_credential_distro_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeToConnectionCredRotator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeToConnectionCredRotator) ProtoMessage() {}

func (x *SubscribeToConnectionCredRotator) ProtoReflect() protoreflect.Message {
	mi := &file_credential_distro_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeToConnectionCredRotator.ProtoReflect.Descriptor instead.
func (*SubscribeToConnectionCredRotator) Descriptor() ([]byte, []int) {
	return file_credential_distro_proto_rawDescGZIP(), []int{1}
}

func (x *SubscribeToConnectionCredRotator) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *SubscribeToConnectionCredRotator) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SubscribeToConnectionCredRotator) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type AckSalt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckSalt) Reset() {
	*x = AckSalt{}
	mi := &file_credential_distro_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckSalt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckSalt) ProtoMessage() {}

func (x *AckSalt) ProtoReflect() protoreflect.Message {
	mi := &file_credential_distro_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckSalt.ProtoReflect.Descriptor instead.
func (*AckSalt) Descriptor() ([]byte, []int) {
	return file_credential_distro_proto_rawDescGZIP(), []int{2}
}

func (x *AckSalt) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AckSalt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AckNewCreds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckNewCreds) Reset() {
	*x = AckNewCreds{}
	mi := &file_credential_distro_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckNewCreds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckNewCreds) ProtoMessage() {}

func (x *AckNewCreds) ProtoReflect() protoreflect.Message {
	mi := &file_credential_distro_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckNewCreds.ProtoReflect.Descriptor instead.
func (*AckNewCreds) Descriptor() ([]byte, []int) {
	return file_credential_distro_proto_rawDescGZIP(), []int{3}
}

func (x *AckNewCreds) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AckNewCreds) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AckConfirm struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	PublicKey     string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckConfirm) Reset() {
	*x = AckConfirm{}
	mi := &file_credential_distro_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckConfirm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckConfirm) ProtoMessage() {}

func (x *AckConfirm) ProtoReflect() protoreflect.Message {
	mi := &file_credential_distro_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckConfirm.ProtoReflect.Descriptor instead.
func (*AckConfirm) Descriptor() ([]byte, []int) {
	return file_credential_distro_proto_rawDescGZIP(), []int{4}
}

func (x *AckConfirm) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AckConfirm) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *AckConfirm) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type NackSalt struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackSalt) Reset() {
	*x = NackSalt{}
	mi := &file_credential_distro_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackSalt) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackSalt) ProtoMessage() {}

func (x *NackSalt) ProtoReflect() protoreflect.Message {
	mi := &file_credential_distro_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackSalt.ProtoReflect.Descriptor instead.
func (*NackSalt) Descriptor() ([]byte, []int) {
	return file_credential_distro_proto_rawDescGZIP(), []int{5}
}

func (x *NackSalt) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *NackSalt) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NackSalt) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type NackNewCreds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Topic         string                 `protobuf:"bytes,1,opt,name=topic,proto3" json:"topic,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Msg           string                 `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackNewCreds) Reset() {
	*x = NackNewCreds{}
	mi := &file_credential_distro_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackNewCreds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackNewCreds) ProtoMessage() {}

func (x *NackNewCreds) ProtoReflect() protoreflect.Message {
	mi := &file_credential_distro_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackNewCreds.ProtoReflect.Descriptor instead.
func (*NackNewCreds) Descriptor() ([]byte, []int) {
	return file_credential_distro_proto_rawDescGZIP(), []int{6}
}

func (x *NackNewCreds) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *NackNewCreds) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NackNewCreds) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type CredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CredentialResponse) Reset() {
	*x = CredentialResponse{}
	mi := &file_credential_distro_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CredentialResponse) ProtoMessage() {}

func (x *CredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credential_distro_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CredentialResponse.ProtoReflect.Descriptor instead.
func (*CredentialResponse) Descriptor() ([]byte, []int) {
	return file_credential_distro_proto_rawDescGZIP(), []int{7}
}

func (x *CredentialResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CredentialResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *CredentialResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type InitialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitialResponse) Reset() {
	*x = InitialResponse{}
	mi := &file_credential_distro_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitialResponse) ProtoMessage() {}

func (x *InitialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credential_distro_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitialResponse.ProtoReflect.Descriptor instead.
func (*InitialResponse) Descriptor() ([]byte, []int) {
	return file_credential_distro_proto_rawDescGZIP(), []int{8}
}

func (x *InitialResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InitialResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *InitialResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type ConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmResponse) Reset() {
	*x = ConfirmResponse{}
	mi := &file_credential_distro_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmResponse) ProtoMessage() {}

func (x *ConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_credential_distro_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmResponse.ProtoReflect.Descriptor instead.
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return file_credential_distro_proto_rawDescGZIP(), []int{9}
}

func (x *ConfirmResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfirmResponse) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

type SaltRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*SaltRequest_SubToSalt
	//	*SaltRequest_AckSalt
	//	*SaltRequest_NackSalt
	Value         isSaltRequest_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaltRequest) Reset() {
	*x = SaltRequest{}
	mi := &file_credential_distro_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaltRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaltRequest) ProtoMessage() {}

func (x *SaltRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credential_distro_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaltRequest.ProtoReflect.Descriptor instead.
func (*SaltRequest) Descriptor() ([]byte, []int) {
	return file_credential_distro_proto_rawDescGZIP(), []int{10}
}

func (x *SaltRequest) GetValue() isSaltRequest_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *SaltRequest) GetSubToSalt() *SubscribeToSaltDistro {
	if x != nil {
		if x, ok := x.Value.(*SaltRequest_SubToSalt); ok {
			return x.SubToSalt
		}
	}
	return nil
}

func (x *SaltRequest) GetAckSalt() *AckSalt {
	if x != nil {
		if x, ok := x.Value.(*SaltRequest_AckSalt); ok {
			return x.AckSalt
		}
	}
	return nil
}

func (x *SaltRequest) GetNackSalt() *NackSalt {
	if x != nil {
		if x, ok := x.Value.(*SaltRequest_NackSalt); ok {
			return x.NackSalt
		}
	}
	return nil
}

type isSaltRequest_Value interface {
	isSaltRequest_Value()
}

type SaltRequest_SubToSalt struct {
	SubToSalt *SubscribeToSaltDistro `protobuf:"bytes,1,opt,name=sub_to_salt,json=subToSalt,proto3,oneof"`
}

type SaltRequest_AckSalt struct {
	AckSalt *AckSalt `protobuf:"bytes,2,opt,name=ack_salt,json=ackSalt,proto3,oneof"`
}

type SaltRequest_NackSalt struct {
	NackSalt *NackSalt `protobuf:"bytes,3,opt,name=nack_salt,json=nackSalt,proto3,oneof"`
}

func (*SaltRequest_SubToSalt) isSaltRequest_Value() {}

func (*SaltRequest_AckSalt) isSaltRequest_Value() {}

func (*SaltRequest_NackSalt) isSaltRequest_Value() {}

type NewCredsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*NewCredsRequest_SubToCredRotator
	//	*NewCredsRequest_AckNewCreds
	//	*NewCredsRequest_NackNewCreds
	//	*NewCredsRequest_AckConfirm
	Value         isNewCredsRequest_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewCredsRequest) Reset() {
	*x = NewCredsRequest{}
	mi := &file_credential_distro_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewCredsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewCredsRequest) ProtoMessage() {}

func (x *NewCredsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_credential_distro_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewCredsRequest.ProtoReflect.Descriptor instead.
func (*NewCredsRequest) Descriptor() ([]byte, []int) {
	return file_credential_distro_proto_rawDescGZIP(), []int{11}
}

func (x *NewCredsRequest) GetValue() isNewCredsRequest_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *NewCredsRequest) GetSubToCredRotator() *SubscribeToConnectionCredRotator {
	if x != nil {
		if x, ok := x.Value.(*NewCredsRequest_SubToCredRotator); ok {
			return x.SubToCredRotator
		}
	}
	return nil
}

func (x *NewCredsRequest) GetAckNewCreds() *AckNewCreds {
	if x != nil {
		if x, ok := x.Value.(*NewCredsRequest_AckNewCreds); ok {
			return x.AckNewCreds
		}
	}
	return nil
}

func (x *NewCredsRequest) GetNackNewCreds() *NackNewCreds {
	if x != nil {
		if x, ok := x.Value.(*NewCredsRequest_NackNewCreds); ok {
			return x.NackNewCreds
		}
	}
	return nil
}

func (x *NewCredsRequest) GetAckConfirm() *AckConfirm {
	if x != nil {
		if x, ok := x.Value.(*NewCredsRequest_AckConfirm); ok {
			return x.AckConfirm
		}
	}
	return nil
}

type isNewCredsRequest_Value interface {
	isNewCredsRequest_Value()
}

type NewCredsRequest_SubToCredRotator struct {
	SubToCredRotator *SubscribeToConnectionCredRotator `protobuf:"bytes,1,opt,name=sub_to_cred_rotator,json=subToCredRotator,proto3,oneof"`
}

type NewCredsRequest_AckNewCreds struct {
	AckNewCreds *AckNewCreds `protobuf:"bytes,2,opt,name=ack_new_creds,json=ackNewCreds,proto3,oneof"`
}

type NewCredsRequest_NackNewCreds struct {
	NackNewCreds *NackNewCreds `protobuf:"bytes,3,opt,name=nack_new_creds,json=nackNewCreds,proto3,oneof"`
}

type NewCredsRequest_AckConfirm struct {
	AckConfirm *AckConfirm `protobuf:"bytes,4,opt,name=ack_confirm,json=ackConfirm,proto3,oneof"`
}

func (*NewCredsRequest_SubToCredRotator) isNewCredsRequest_Value() {}

func (*NewCredsRequest_AckNewCreds) isNewCredsRequest_Value() {}

func (*NewCredsRequest_NackNewCreds) isNewCredsRequest_Value() {}

func (*NewCredsRequest_AckConfirm) isNewCredsRequest_Value() {}

type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*Response_Response
	//	*Response_Confirm
	//	*Response_InitialResponse
	Value         isResponse_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_credential_distro_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_credential_distro_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_credential_distro_proto_rawDescGZIP(), []int{12}
}

func (x *Response) GetValue() isResponse_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Response) GetResponse() *CredentialResponse {
	if x != nil {
		if x, ok := x.Value.(*Response_Response); ok {
			return x.Response
		}
	}
	return nil
}

func (x *Response) GetConfirm() *ConfirmResponse {
	if x != nil {
		if x, ok := x.Value.(*Response_Confirm); ok {
			return x.Confirm
		}
	}
	return nil
}

func (x *Response) GetInitialResponse() *InitialResponse {
	if x != nil {
		if x, ok := x.Value.(*Response_InitialResponse); ok {
			return x.InitialResponse
		}
	}
	return nil
}

type isResponse_Value interface {
	isResponse_Value()
}

type Response_Response struct {
	Response *CredentialResponse `protobuf:"bytes,1,opt,name=response,proto3,oneof"`
}

type Response_Confirm struct {
	Confirm *ConfirmResponse `protobuf:"bytes,2,opt,name=confirm,proto3,oneof"`
}

type Response_InitialResponse struct {
	InitialResponse *InitialResponse `protobuf:"bytes,3,opt,name=initial_response,json=initialResponse,proto3,oneof"`
}

func (*Response_Response) isResponse_Value() {}

func (*Response_Confirm) isResponse_Value() {}

func (*Response_InitialResponse) isResponse_Value() {}

var File_credential_distro_proto protoreflect.FileDescriptor

const file_credential_distro_proto_rawDesc = "" +
	"\n" +
	"\x17credential_distro.proto\x12\x15user_registry_service\"=\n" +
	"\x15SubscribeToSaltDistro\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"g\n" +
	" SubscribeToConnectionCredRotator\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\"/\n" +
	"\aAckSalt\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"3\n" +
	"\vAckNewCreds\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\"Q\n" +
	"\n" +
	"AckConfirm\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\"B\n" +
	"\bNackSalt\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"F\n" +
	"\fNackNewCreds\x12\x14\n" +
	"\x05topic\x18\x01 \x01(\tR\x05topic\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x10\n" +
	"\x03msg\x18\x03 \x01(\tR\x03msg\"T\n" +
	"\x12CredentialResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"Q\n" +
	"\x0fInitialResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"7\n" +
	"\x0fConfirmResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\"\xe3\x01\n" +
	"\vSaltRequest\x12N\n" +
	"\vsub_to_salt\x18\x01 \x01(\v2,.user_registry_service.SubscribeToSaltDistroH\x00R\tsubToSalt\x12;\n" +
	"\back_salt\x18\x02 \x01(\v2\x1e.user_registry_service.AckSaltH\x00R\aackSalt\x12>\n" +
	"\tnack_salt\x18\x03 \x01(\v2\x1f.user_registry_service.NackSaltH\x00R\bnackSaltB\a\n" +
	"\x05value\"\xe1\x02\n" +
	"\x0fNewCredsRequest\x12h\n" +
	"\x13sub_to_cred_rotator\x18\x01 \x01(\v27.user_registry_service.SubscribeToConnectionCredRotatorH\x00R\x10subToCredRotator\x12H\n" +
	"\rack_new_creds\x18\x02 \x01(\v2\".user_registry_service.AckNewCredsH\x00R\vackNewCreds\x12K\n" +
	"\x0enack_new_creds\x18\x03 \x01(\v2#.user_registry_service.NackNewCredsH\x00R\fnackNewCreds\x12D\n" +
	"\vack_confirm\x18\x04 \x01(\v2!.user_registry_service.AckConfirmH\x00R\n" +
	"ackConfirmB\a\n" +
	"\x05value\"\xf5\x01\n" +
	"\bResponse\x12G\n" +
	"\bresponse\x18\x01 \x01(\v2).user_registry_service.CredentialResponseH\x00R\bresponse\x12B\n" +
	"\aconfirm\x18\x02 \x01(\v2&.user_registry_service.ConfirmResponseH\x00R\aconfirm\x12S\n" +
	"\x10initial_response\x18\x03 \x01(\v2&.user_registry_service.InitialResponseH\x00R\x0finitialResponseB\a\n" +
	"\x05value2\xcf\x01\n" +
	"\x17CredentialDistroService\x12U\n" +
	"\n" +
	"SaltStream\x12\".user_registry_service.SaltRequest\x1a\x1f.user_registry_service.Response(\x010\x01\x12]\n" +
	"\x0eNewCredsStream\x12&.user_registry_service.NewCredsRequest\x1a\x1f.user_registry_service.Response(\x010\x01B\tZ\a./protob\x06proto3"

var (
	file_credential_distro_proto_rawDescOnce sync.Once
	file_credential_distro_proto_rawDescData []byte
)

func file_credential_distro_proto_rawDescGZIP() []byte {
	file_credential_distro_proto_rawDescOnce.Do(func() {
		file_credential_distro_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_credential_distro_proto_rawDesc), len(file_credential_distro_proto_rawDesc)))
	})
	return file_credential_distro_proto_rawDescData
}

var file_credential_distro_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_credential_distro_proto_goTypes = []any{
	(*SubscribeToSaltDistro)(nil),            // 0: user_registry_service.SubscribeToSaltDistro
	(*SubscribeToConnectionCredRotator)(nil), // 1: user_registry_service.SubscribeToConnectionCredRotator
	(*AckSalt)(nil),                          // 2: user_registry_service.AckSalt
	(*AckNewCreds)(nil),                      // 3: user_registry_service.AckNewCreds
	(*AckConfirm)(nil),                       // 4: user_registry_service.AckConfirm
	(*NackSalt)(nil),                         // 5: user_registry_service.NackSalt
	(*NackNewCreds)(nil),                     // 6: user_registry_service.NackNewCreds
	(*CredentialResponse)(nil),               // 7: user_registry_service.CredentialResponse
	(*InitialResponse)(nil),                  // 8: user_registry_service.InitialResponse
	(*ConfirmResponse)(nil),                  // 9: user_registry_service.ConfirmResponse
	(*SaltRequest)(nil),                      // 10: user_registry_service.SaltRequest
	(*NewCredsRequest)(nil),                  // 11: user_registry_service.NewCredsRequest
	(*Response)(nil),                         // 12: user_registry_service.Response
}
var file_credential_distro_proto_depIdxs = []int32{
	0,  // 0: user_registry_service.SaltRequest.sub_to_salt:type_name -> user_registry_service.SubscribeToSaltDistro
	2,  // 1: user_registry_service.SaltRequest.ack_salt:type_name -> user_registry_service.AckSalt
	5,  // 2: user_registry_service.SaltRequest.nack_salt:type_name -> user_registry_service.NackSalt
	1,  // 3: user_registry_service.NewCredsRequest.sub_to_cred_rotator:type_name -> user_registry_service.SubscribeToConnectionCredRotator
	3,  // 4: user_registry_service.NewCredsRequest.ack_new_creds:type_name -> user_registry_service.AckNewCreds
	6,  // 5: user_registry_service.NewCredsRequest.nack_new_creds:type_name -> user_registry_service.NackNewCreds
	4,  // 6: user_registry_service.NewCredsRequest.ack_confirm:type_name -> user_registry_service.AckConfirm
	7,  // 7: user_registry_service.Response.response:type_name -> user_registry_service.CredentialResponse
	9,  // 8: user_registry_service.Response.confirm:type_name -> user_registry_service.ConfirmResponse
	8,  // 9: user_registry_service.Response.initial_response:type_name -> user_registry_service.InitialResponse
	10, // 10: user_registry_service.CredentialDistroService.SaltStream:input_type -> user_registry_service.SaltRequest
	11, // 11: user_registry_service.CredentialDistroService.NewCredsStream:input_type -> user_registry_service.NewCredsRequest
	12, // 12: user_registry_service.CredentialDistroService.SaltStream:output_type -> user_registry_service.Response
	12, // 13: user_registry_service.CredentialDistroService.NewCredsStream:output_type -> user_registry_service.Response
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_credential_distro_proto_init() }
func file_credential_distro_proto_init() {
	if File_credential_distro_proto != nil {
		return
	}
	file_credential_distro_proto_msgTypes[10].OneofWrappers = []any{
		(*SaltRequest_SubToSalt)(nil),
		(*SaltRequest_AckSalt)(nil),
		(*SaltRequest_NackSalt)(nil),
	}
	file_credential_distro_proto_msgTypes[11].OneofWrappers = []any{
		(*NewCredsRequest_SubToCredRotator)(nil),
		(*NewCredsRequest_AckNewCreds)(nil),
		(*NewCredsRequest_NackNewCreds)(nil),
		(*NewCredsRequest_AckConfirm)(nil),
	}
	file_credential_distro_proto_msgTypes[12].OneofWrappers = []any{
		(*Response_Response)(nil),
		(*Response_Confirm)(nil),
		(*Response_InitialResponse)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_credential_distro_proto_rawDesc), len(file_credential_distro_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_credential_distro_proto_goTypes,
		DependencyIndexes: file_credential_distro_proto_depIdxs,
		MessageInfos:      file_credential_distro_proto_msgTypes,
	}.Build()
	File_credential_distro_proto = out.File
	file_credential_distro_proto_goTypes = nil
	file_credential_distro_proto_depIdxs = nil
}
