// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.0
// source: credential_distro.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CredentialDistroService_SaltStream_FullMethodName     = "/user_registry_service.CredentialDistroService/SaltStream"
	CredentialDistroService_NewCredsStream_FullMethodName = "/user_registry_service.CredentialDistroService/NewCredsStream"
)

// CredentialDistroServiceClient is the client API for CredentialDistroService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CredentialDistroServiceClient interface {
	SaltStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SaltRequest, Response], error)
	NewCredsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NewCredsRequest, Response], error)
}

type credentialDistroServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCredentialDistroServiceClient(cc grpc.ClientConnInterface) CredentialDistroServiceClient {
	return &credentialDistroServiceClient{cc}
}

func (c *credentialDistroServiceClient) SaltStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[SaltRequest, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CredentialDistroService_ServiceDesc.Streams[0], CredentialDistroService_SaltStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SaltRequest, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CredentialDistroService_SaltStreamClient = grpc.BidiStreamingClient[SaltRequest, Response]

func (c *credentialDistroServiceClient) NewCredsStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[NewCredsRequest, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CredentialDistroService_ServiceDesc.Streams[1], CredentialDistroService_NewCredsStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[NewCredsRequest, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CredentialDistroService_NewCredsStreamClient = grpc.BidiStreamingClient[NewCredsRequest, Response]

// CredentialDistroServiceServer is the server API for CredentialDistroService service.
// All implementations must embed UnimplementedCredentialDistroServiceServer
// for forward compatibility.
type CredentialDistroServiceServer interface {
	SaltStream(grpc.BidiStreamingServer[SaltRequest, Response]) error
	NewCredsStream(grpc.BidiStreamingServer[NewCredsRequest, Response]) error
	mustEmbedUnimplementedCredentialDistroServiceServer()
}

// UnimplementedCredentialDistroServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCredentialDistroServiceServer struct{}

func (UnimplementedCredentialDistroServiceServer) SaltStream(grpc.BidiStreamingServer[SaltRequest, Response]) error {
	return status.Errorf(codes.Unimplemented, "method SaltStream not implemented")
}
func (UnimplementedCredentialDistroServiceServer) NewCredsStream(grpc.BidiStreamingServer[NewCredsRequest, Response]) error {
	return status.Errorf(codes.Unimplemented, "method NewCredsStream not implemented")
}
func (UnimplementedCredentialDistroServiceServer) mustEmbedUnimplementedCredentialDistroServiceServer() {
}
func (UnimplementedCredentialDistroServiceServer) testEmbeddedByValue() {}

// UnsafeCredentialDistroServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CredentialDistroServiceServer will
// result in compilation errors.
type UnsafeCredentialDistroServiceServer interface {
	mustEmbedUnimplementedCredentialDistroServiceServer()
}

func RegisterCredentialDistroServiceServer(s grpc.ServiceRegistrar, srv CredentialDistroServiceServer) {
	// If the following call pancis, it indicates UnimplementedCredentialDistroServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CredentialDistroService_ServiceDesc, srv)
}

func _CredentialDistroService_SaltStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CredentialDistroServiceServer).SaltStream(&grpc.GenericServerStream[SaltRequest, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CredentialDistroService_SaltStreamServer = grpc.BidiStreamingServer[SaltRequest, Response]

func _CredentialDistroService_NewCredsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CredentialDistroServiceServer).NewCredsStream(&grpc.GenericServerStream[NewCredsRequest, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CredentialDistroService_NewCredsStreamServer = grpc.BidiStreamingServer[NewCredsRequest, Response]

// CredentialDistroService_ServiceDesc is the grpc.ServiceDesc for CredentialDistroService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CredentialDistroService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user_registry_service.CredentialDistroService",
	HandlerType: (*CredentialDistroServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SaltStream",
			Handler:       _CredentialDistroService_SaltStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "NewCredsStream",
			Handler:       _CredentialDistroService_NewCredsStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "credential_distro.proto",
}
