CREATE TABLE IF NOT EXISTS users(
    id BINARY(16) PRIMARY KEY,
    entity VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS profiles(
    id BINARY(16) PRIMARY KEY,
    bio TEXT NOT NULL,
    user_id BINARY(16) NOT NULL UNIQUE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS contacts(
    id BINARY(16) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    image_file_path VARCHAR(255) NOT NULL UNIQUE,
    profile_id BINARY(16) NOT NULL UNIQUE,
    FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);