# Basisimage: .NET SDK 9.0
FROM mcr.microsoft.com/dotnet/sdk:9.0

USER root

# Pakete installieren: Docker CLI und Git
RUN apt-get update && \
    apt-get install -y docker.io git && \
    rm -rf /var/lib/apt/lists/*

USER jenkins

COPY . .