// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Contact struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Email         string `json:"email"`
	ImageFilePath string `json:"imageFilePath"`
}

type Profile struct {
	ID      string   `json:"id"`
	Bio     string   `json:"bio"`
	Contact *Contact `json:"contact"`
}

type Query struct {
}

type User struct {
	ID      string   `json:"id"`
	Profile *Profile `json:"profile"`
}

type UserEntity struct {
	User string `json:"user"`
}
