// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CompleteWorkspace struct {
	ID       string            `json:"id"`
	Name     string            `json:"name"`
	Contacts []*Contact        `json:"contacts"`
	News     []*InvitationInfo `json:"news"`
}

type Contact struct {
	ID            string `json:"id"`
	Name          string `json:"name"`
	Email         string `json:"email"`
	ImageFilePath string `json:"imageFilePath"`
}

type Invitation struct {
	ID   string `json:"id"`
	Info string `json:"info"`
}

type InvitationCredentials struct {
	InvitorID   string `json:"invitorID"`
	ReceiverID  string `json:"receiverID"`
	WorkspaceID string `json:"workspaceID"`
	Info        string `json:"info"`
}

type InvitationInfo struct {
	ID   string `json:"id"`
	Info string `json:"info"`
}

type JoinRequest struct {
	ID     string `json:"id"`
	Info   string `json:"info"`
	Reason string `json:"reason"`
}

type JoinRequestCredentials struct {
	WorkspaceID string `json:"workspaceID"`
	RequestID   string `json:"requestID"`
	Info        string `json:"info"`
	Reason      string `json:"reason"`
}

type JoinRequestInfo struct {
	ID   string `json:"id"`
	Info string `json:"info"`
}

type Mutation struct {
}

type Profile struct {
	ID      string   `json:"id"`
	Bio     string   `json:"bio"`
	Contact *Contact `json:"contact"`
}

type Query struct {
}

type User struct {
	ID         string       `json:"id"`
	Entity     string       `json:"entity"`
	Profile    *Profile     `json:"profile"`
	Workspaces []*Workspace `json:"workspaces"`
}

type Workspace struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type WorkspaceCredentials struct {
	UserID string `json:"userID"`
	Name   string `json:"name"`
}
