// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Contact struct {
	ID       string `json:"id"`
	Name     string `json:"name"`
	Email    string `json:"email"`
	HasImage string `json:"hasImage"`
}

type InvitationCredentials struct {
	Subject     string `json:"subject"`
	Message     string `json:"message"`
	WorkspaceID string `json:"workspaceID"`
	UserID      string `json:"userID"`
	ContactID   string `json:"contactID"`
}

type Invitations struct {
	ID          string `json:"id"`
	Subject     string `json:"subject"`
	Message     string `json:"message"`
	WorkspaceID string `json:"workspaceID"`
	ContactID   string `json:"contactID"`
}

type JoinRequestCredentials struct {
	Subject     string `json:"subject"`
	Message     string `json:"message"`
	WorksapceID string `json:"worksapceID"`
	ProfileID   string `json:"profileID"`
}

type JoinRequests struct {
	ID          string `json:"id"`
	Subject     string `json:"subject"`
	Message     string `json:"message"`
	ProfileID   string `json:"profileID"`
	WorksapceID string `json:"worksapceID"`
}

type Mutation struct {
}

type Profile struct {
	ID      string   `json:"id"`
	Bio     string   `json:"bio"`
	Contact *Contact `json:"contact"`
}

type Query struct {
}

type User struct {
	ID      string   `json:"id"`
	Entity  string   `json:"entity"`
	Profile *Profile `json:"profile"`
}

type UserEntity struct {
	User string `json:"user"`
}

type Workspace struct {
	ID                string     `json:"id"`
	Name              string     `json:"name"`
	Description       string     `json:"description"`
	JoinrequestCopunt int        `json:"joinrequestCopunt"`
	Contacts          []*Contact `json:"contacts"`
}

type WorkspaceCredentials struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	UserID      string `json:"userID"`
}
