package sessionimpl

import "github.com/google/uuid"

type Adapter interface {
	// tries to fetch verify data. you'll get the account id the session id and the verify number string on success
	// if the fetch failed you get an error
	GetVerifyData(cookie string) (uuid.UUID, string, string, error)

	// deletes a verify session. if no session with this id is in this store you get an error
	DeleteVerifySession(id string) error

	// adds a new set of verify data in the store.
	// the data will be generated by the session.
	// you will get an cookie string and a verify number string on success otherwice an error
	SetVerifyData(accountID string) (string, string, error)

	// set new refresh data for the refresh session.
	// you will get a cookie string on success otherwice you'll get an error
	SetRefreshData(accountID, ip, userAgent string) (string, error)

	// checks if the verify session is correct.
	// on success it sets up a new refresh cookie and a refresch session otherwice you'll get an error
	VerifyRefreshData(cookie, ip, userAgent string) (string, error)

	// removes the refresh data
	RemoveRefreshData(cookie, ip, userAgent string) error

	// cleans up the service on server shutdown or reconnect
	CloseSession() error

	// registers and computes background services like intervalls and key exchanges
	HandleBackground()
}
