POST http://localhost:4000/account/new_verify
Content-Type: application/json

{
    "email": "invalid"
}

###

POST http://localhost:4000/account/new_verify
Content-Type: application/json

{
    "email": "valid"
}