
# invalid password requests
# chars in password not various enough
POST http://localhost:4000/account/signup
Content-Type: application/json

{
    "name": "gerri",
    "email": "some.email@provider.com",
    "password": "invalid",
    "confirmation": "invalid"
}

###

# not enough chars in password
POST http://localhost:4000/account/signup
Content-Type: application/json

{
    "name": "gerri",
    "email": "some.email@some.provider.com",
    "password": "H@ll0",
    "confirmation": "H@ll0"
}

###

# password and confirmation does not match
POST http://localhost:4000/account/signup
Content-Type: application/json

{
    "name": "gerri",
    "email": "some.email@someprovider.com",
    "password": "H4ll!H@ll0",
    "confirmation": "NotMatchingPassword"
}

###

# successful signup
POST http://localhost:4000/account/signup
Content-Type: application/json

{
    "name": "gerri",
    "email": "some.email3@provider.com",
    "password": "F!sh@ndCh1ps",
    "confirmation": "F!sh@ndCh1ps"
}