# invalid password request
POST http://localhost:4000/account/signin
Content-Type: application/json

{
    "email": "some.email@provider.com",
    "password": "invalid"
}

###

# account not found request
POST http://localhost:4000/account/signin
Content-Type: application/json

{
    "email": "invalid",
    "password": "F!sh@ndCh1ps"
}

###

# successful signin
POST http://localhost:4000/account/signin
Content-Type: application/json

{
    "email": "some.email11@provider.com",
    "password": "F!sh@ndCh1ps"
}